### ISSUE TITLE
Template selector for 'Create Prenotification PDF' button

### ISSUE THREAD

**Issue by systopia** [Project60/sepa_dd#188]
The button in the 'mandate options' panel only uses the predefined template. However, we have scenarios where it would be important to be able to choose the template you want to use.

**Comment by systopia** [comment]
@nikobo I get an exception with the current master:
```
#0 /Users/didonai/Documents/mamp_root/rowo/sites/all/modules/civicrm/CRM/Core/Error.php(315): CRM_Core_Error::backtrace()
#1 /Users/didonai/Documents/mamp_root/rowo/sites/all/modules/civicrm/CRM/Utils/Type.php(326): CRM_Core_Error::fatal("tpl (value: undefined) is not of the type Positive")
#2 /Users/didonai/Documents/mamp_root/rowo/sites/all/modules/civicrm/CRM/Utils/Request.php(96): CRM_Utils_Type::validate("undefined", "Positive", TRUE, "tpl")
#3 /Users/didonai/Documents/workspace/CiviSEPA/CRM/Sepa/Page/SepaMandatePdf.php(131): CRM_Utils_Request::retrieve("tpl", "Positive", Object(CRM_Sepa_Page_SepaMandatePdf), TRUE)
#4 /Users/didonai/Documents/mamp_root/rowo/sites/all/modules/civicrm/CRM/Core/Invoke.php(323): CRM_Sepa_Page_SepaMandatePdf->run((Array:3), NULL)
#5 /Users/didonai/Documents/mamp_root/rowo/sites/all/modules/civicrm/CRM/Core/Invoke.php(72): CRM_Core_Invoke::runItem((Array:13))
#6 /Users/didonai/Documents/mamp_root/rowo/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#7 /Users/didonai/Documents/mamp_root/rowo/sites/all/modules/civicrm/drupal/civicrm.module(456): CRM_Core_Invoke::invoke((Array:3))
#8 [internal function](): civicrm_invoke("sepa", "pdf")
#9 /Users/didonai/Documents/mamp_root/rowo/includes/menu.inc(517): call_user_func_array("civicrm_invoke", (Array:2))
#10 /Users/didonai/Documents/mamp_root/rowo/index.php(21): menu_execute_active_handler()
#11 {main}
```
