### ISSUE TITLE
Payment processor causes DB error in 4.4.6

### ISSUE THREAD

**Issue by systopia** [Project60/sepa_dd#226]
When working with the payment processor on CiviCRM <= 4.4.6 you will be affected by [CRM-14986](https://issues.civicrm.org/jira/browse/CRM-14986), which causes the payment process to fail with an "Incorrect datetime value" error. 

A typical stack trace would look as follows:
```
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /var/www/drupal04/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 /var/www/drupal04/sites/all/modules/civicrm/packages/DB.php(969): PEAR_Error->PEAR_Error("DB Error: unknown error", -1, 16, (Array:2), "UPDATE  civicrm_contribution  SET contact_id = 1851 , financial_type_id = 5 ,...")
#4 /var/www/drupal04/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-1, 16, (Array:2), "UPDATE  civicrm_contribution  SET contact_id = 1851 , financial_type_id = 5 ,...")
#5 /var/www/drupal04/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -1, NULL, NULL, "UPDATE  civicrm_contribution  SET contact_id = 1851 , financial_type_id = 5 ,...", "DB_Error", TRUE)
#6 /var/www/drupal04/sites/all/modules/civicrm/packages/DB/mysql.php(898): DB_common->raiseError(-1, NULL, NULL, NULL, "1292 ** Incorrect datetime value: '2014' for column 'receipt_date' at row 1")
#7 /var/www/drupal04/sites/all/modules/civicrm/packages/DB/mysql.php(327): DB_mysql->mysqlRaiseError()
#8 /var/www/drupal04/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("UPDATE  civicrm_contribution  SET contact_id = 1851 , financial_type_id = 5 ,...")
#9 /var/www/drupal04/sites/all/modules/civicrm/packages/DB/DataObject.php(2421): DB_common->query("UPDATE  civicrm_contribution  SET contact_id = 1851 , financial_type_id = 5 ,...")
#10 /var/www/drupal04/sites/all/modules/civicrm/packages/DB/DataObject.php(1324): DB_DataObject->_query("UPDATE  civicrm_contribution  SET contact_id = 1851 , financial_type_id = 5 ,...")
#11 /var/www/drupal04/sites/all/modules/civicrm/CRM/Core/DAO.php(275): DB_DataObject->update()
#12 /var/www/drupal04/sites/default/extensions/sepa_dd/CRM/Core/Payment/SDD.php(229): CRM_Core_DAO->save()
#13 /var/www/drupal04/sites/default/extensions/sepa_dd/sepa_pp_sdd.php(135): CRM_Core_Payment_SDD::processPartialMandates()
#14 /var/www/drupal04/sites/default/extensions/sepa_dd/sepa.php(77): sepa_pp_postProcess("CRM_Contribute_Form_Contribution_Confirm", Object(CRM_Contribute_Form_Contribution_Confirm))
#15 /var/www/drupal04/sites/all/modules/civicrm/CRM/Utils/Hook.php(152): sepa_civicrm_postProcess("CRM_Contribute_Form_Contribution_Confirm", Object(CRM_Contribute_Form_Contribution_Confirm))
#16 /var/www/drupal04/sites/all/modules/civicrm/CRM/Utils/Hook/Drupal.php(67): CRM_Utils_Hook->runHooks((Array:33), "civicrm_postProcess", 2, "CRM_Contribute_Form_Contribution_Confirm", Object(CRM_Contribute_Form_Contribution_Confirm), "CRM_Contribute_Form_Contribution_Confirm", "CRM_Contribute_Form_Contribution_Confirm", "CRM_Contribute_Form_Contribution_Confirm")
#17 /var/www/drupal04/sites/all/modules/civicrm/CRM/Utils/Hook.php(270): CRM_Utils_Hook_Drupal->invoke(2, "CRM_Contribute_Form_Contribution_Confirm", Object(CRM_Contribute_Form_Contribution_Confirm), "CRM_Contribute_Form_Contribution_Confirm", "CRM_Contribute_Form_Contribution_Confirm", "CRM_Contribute_Form_Contribution_Confirm", "civicrm_postProcess")
#18 /var/www/drupal04/sites/all/modules/civicrm/CRM/Core/Form.php(275): CRM_Utils_Hook::postProcess("CRM_Contribute_Form_Contribution_Confirm", Object(CRM_Contribute_Form_Contribution_Confirm))
#19 /var/www/drupal04/sites/all/modules/civicrm/CRM/Core/Form.php(263): CRM_Core_Form->postProcessHook()
#20 /var/www/drupal04/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#21 /var/www/drupal04/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(60): CRM_Core_StateMachine->perform(Object(CRM_Contribute_Form_Contribution_Confirm), "next", "Next")
#22 /var/www/drupal04/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Contribute_Form_Contribution_Confirm), "next")
#23 /var/www/drupal04/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Contribute_Form_Contribution_Confirm), "next")
#24 /var/www/drupal04/sites/all/modules/civicrm/CRM/Core/Controller.php(339): HTML_QuickForm_Page->handle("next")
#25 /var/www/drupal04/sites/all/modules/civicrm/CRM/Core/Invoke.php(323): CRM_Core_Controller->run((Array:3), NULL)
#26 /var/www/drupal04/sites/all/modules/civicrm/CRM/Core/Invoke.php(72): CRM_Core_Invoke::runItem((Array:15))
#27 /var/www/drupal04/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#28 /var/www/drupal04/sites/all/modules/civicrm/drupal/civicrm.module(456): CRM_Core_Invoke::invoke((Array:3))
#29 [internal function](): civicrm_invoke("contribute", "transact")
#30 /var/www/drupal04/includes/menu.inc(517): call_user_func_array("civicrm_invoke", (Array:2))
#31 /var/www/drupal04/index.php(21): menu_execute_active_handler()
#32 {main}
```

**Comment by systopia** [comment]
Since the problem is resolved in CiviCRM 4.4.7, we won't include a workaround into the SEPA module.
